export { default as SpoonAndFork } from "./spoon-and-fork-svgrepo-com.svg"
export { default as HamburgerIcon } from "./icons8-menu.svg"
export { default as UserIcon } from "./user.svg"
export { default as ChevronLeft } from "./chevron-left.svg"
export { default as ChevronRight } from "./chevron-right.svg"
